# Parameters for your particle filter

motion_params:
  vel_std:    0.02
  delta_std:  0.1
  x_std:      0.02
  y_std:      0.02
  theta_std:  0.02

sensor_params:
  hit_std:    2.5
  z_hit:      20.5
  z_short:    0.05
  z_max:      20.01
  z_rand:     20.5
